/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TodoRemovedEvent } from "./components/todo-task-card/todo-removed-event";
export { TodoRemovedEvent } from "./components/todo-task-card/todo-removed-event";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TodoTaskCard {
    }
}
export interface TodoTaskCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTodoTaskCardElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTodoTaskCardElement extends Components.TodoTaskCard, HTMLStencilElement {
    }
    var HTMLTodoTaskCardElement: {
        prototype: HTMLTodoTaskCardElement;
        new (): HTMLTodoTaskCardElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "todo-task-card": HTMLTodoTaskCardElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TodoTaskCard {
        "onTodoRemoved"?: (event: TodoTaskCardCustomEvent<TodoRemovedEvent>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "todo-task-card": TodoTaskCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "todo-task-card": LocalJSX.TodoTaskCard & JSXBase.HTMLAttributes<HTMLTodoTaskCardElement>;
        }
    }
}
